
export const countriesData = [
    {
        code: "+93",
        countryCode: "AF",
        name: "Afghanistan",
        level: "Level 4: Very High",
    },
    {
        code: "+355",
        countryCode: "AL",
        name: "Albania",
        level: "Level 4: Very High",
    },
    {
        code: "+213",
        countryCode: "DZ",
        name: "Algeria",
        level: "Level 4: Very High",
    },
    {
        code: "+1684",
        countryCode: "AS",
        name: "American Samoa",
        level: "Level 1: Low",
    },
    {
        code: "+376",
        countryCode: "AD",
        name: "Andorra",
        level: "Level 4: Very High",
    },
    {
        code: "+244",
        countryCode: "AO",
        name: "Angola",
        level: "Level 4: Very High",
    },
    { code: "+1264", countryCode: "AI", name: "Anguilla", level: "Level 1: Low" },
    {
        code: "+672",
        countryCode: "AQ",
        name: "Antarctica",
        level: "Level 1: Low",
    },
    {
        code: "+1268",
        countryCode: "AG",
        name: "Antigua and Barbuda",
        level: "Level 2: Moderate",
    },
    {
        code: "+54",
        countryCode: "AR",
        name: "Argentina",
        level: "Level 4: Very High",
    },
    {
        code: "+374",
        countryCode: "AM",
        name: "Armenia",
        level: "Level 4: Very High",
    },
    {
        code: "+297",
        countryCode: "AW",
        name: "Aruba",
        level: "Level 4: Very High",
    },
    { code: "+61", countryCode: "AU", name: "Australia", level: "Level 1: Low" },
    {
        code: "+43",
        countryCode: "AT",
        name: "Austria",
        level: "Level 4: Very High",
    },
    {
        code: "+994",
        countryCode: "AZ",
        name: "Azerbaijan",
        level: "Level 4: Very High",
    },
    { level: "Level 0: Unknow", name: "Azores", code: "+351" },
    {
        code: "+1242",
        countryCode: "BS",
        name: "Bahamas",
        level: "Level 4: Very High",
    },
    {
        code: "+973",
        countryCode: "BH",
        name: "Bahrain",
        level: "Level 4: Very High",
    },
    {
        code: "+880",
        countryCode: "BD",
        name: "Bangladesh",
        level: "Level 4: Very High",
    },
    {
        code: "+1246",
        countryCode: "BB",
        name: "Barbados",
        level: "Level 2: Moderate",
    },
    {
        code: "+375",
        countryCode: "BY",
        name: "Belarus",
        level: "Level 4: Very High",
    },
    {
        code: "+32",
        countryCode: "BE",
        name: "Belgium",
        level: "Level 4: Very High",
    },
    {
        code: "+501",
        countryCode: "BZ",
        name: "Belize",
        level: "Level 4: Very High",
    },
    { code: "+229", countryCode: "BJ", name: "Benin", level: "Level 1: Low" },
    { code: "+1441", countryCode: "BM", name: "Bermuda", level: "Level 1: Low" },
    {
        code: "+975",
        countryCode: "BT",
        name: "Bhutan",
        level: "Level 4: Very High",
    },
    {
        code: "+591",
        countryCode: "BO",
        name: "Bolivia, Plurinational State of bolivia",
        level: "Level 4: Very High",
    },
    { level: "Level 4: Very High", name: "Bonaire", code: "+599" },
    {
        code: "+387",
        countryCode: "BA",
        name: "Bosnia and Herzegovina",
        level: "Level 4: Very High",
    },
    {
        code: "+267",
        countryCode: "BW",
        name: "Botswana",
        level: "Level 4: Very High",
    },
    {
        code: "+55",
        countryCode: "BR",
        name: "Brazil",
        level: "Level 4: Very High",
    },
    {
        code: "+246",
        countryCode: "IO",
        name: "British Indian Ocean Territory",
        level: "Level 0: Unknow",
    },
    { level: "Level 1: Low", name: "British Virgin Islands", code: "+1" },
    { code: "+673", countryCode: "BN", name: "Brunei", level: "Level 1: Low" },
    {
        code: "+359",
        countryCode: "BG",
        name: "Bulgaria",
        level: "Level 4: Very High",
    },
    {
        code: "+226",
        countryCode: "BF",
        name: "Burkina Faso",
        level: "Level 4: Very High",
    },
    { level: "Level 4: Very High", name: "Myanmar", code: "+95" },
    {
        code: "+257",
        countryCode: "BI",
        name: "Burundi",
        level: "Level 4: Very High",
    },
    { code: "+855", countryCode: "KH", name: "Cambodia", level: "Level 1: Low" },
    {
        code: "+237",
        countryCode: "CM",
        name: "Cameroon",
        level: "Level 4: Very High",
    },
    {
        code: "+1",
        countryCode: "CA",
        name: "Canada",
        level: "Level 4: Very High",
    },
    { level: "Level 0: Unknow", name: "Canary Islands", code: "+34" },
    {
        code: "+238",
        countryCode: "CV",
        name: "Cape Verde",
        level: "Level 4: Very High",
    },
    {
        code: "+ 345",
        countryCode: "KY",
        name: "Cayman Islands",
        level: "Level 1: Low",
    },
    {
        code: "+236",
        countryCode: "CF",
        name: "Central African Republic",
        level: "Level 4: Very High",
    },
    {
        code: "+235",
        countryCode: "TD",
        name: "Chad",
        level: "Level 4: Very High",
    },
    {
        code: "+56",
        countryCode: "CL",
        name: "Chile",
        level: "Level 4: Very High",
    },
    { code: "+86", countryCode: "CN", name: "China", level: "Level 1: Low" },
    {
        code: "+61",
        countryCode: "CX",
        name: "Christmas Island",
        level: "Level 0: Unknow",
    },
    {
        code: "+61",
        countryCode: "CC",
        name: "Cocos (Keeling) Islands",
        level: "Level 0: Unknow",
    },
    {
        code: "+57",
        countryCode: "CO",
        name: "Colombia",
        level: "Level 4: Very High",
    },
    {
        code: "+269",
        countryCode: "KM",
        name: "Comoros",
        level: "Level 4: Very High",
    },
    {
        code: "+242",
        countryCode: "CG",
        name: "Congo",
        level: "Level 4: Very High",
    },
    {
        code: "+682",
        countryCode: "CK",
        name: "Cook Islands",
        level: "Level 1: Low",
    },
    {
        code: "+506",
        countryCode: "CR",
        name: "Costa Rica",
        level: "Level 4: Very High",
    },
    {
        code: "+385",
        countryCode: "HR",
        name: "Croatia",
        level: "Level 4: Very High",
    },
    { code: "+53", countryCode: "CU", name: "Cuba", level: "Level 4: Very High" },
    { level: "Level 4: Very High", name: "Curaçao", code: "+599" },
    {
        code: "+357",
        countryCode: "CY",
        name: "Cyprus",
        level: "Level 4: Very High",
    },
    {
        code: "+420",
        countryCode: "CZ",
        name: "Czech Republic",
        level: "Level 4: Very High",
    },
    {
        code: "+243",
        countryCode: "CD",
        name: "Congo, The Democratic Republic of the Congo",
        level: "Level 4: Very High",
    },
    {
        code: "+45",
        countryCode: "DK",
        name: "Denmark",
        level: "Level 4: Very High",
    },
    {
        code: "+253",
        countryCode: "DJ",
        name: "Djibouti",
        level: "Level 4: Very High",
    },
    {
        code: "+1767",
        countryCode: "DM",
        name: "Dominica",
        level: "Level 2: Moderate",
    },
    {
        code: "+1849",
        countryCode: "DO",
        name: "Dominican Republic",
        level: "Level 4: Very High",
    },
    { level: "Level 4: Very High", name: "Easter Island", code: "+56" },
    {
        code: "+593",
        countryCode: "EC",
        name: "Ecuador",
        level: "Level 4: Very High",
    },
    {
        code: "+20",
        countryCode: "EG",
        name: "Egypt",
        level: "Level 4: Very High",
    },
    {
        code: "+503",
        countryCode: "SV",
        name: "El Salvador",
        level: "Level 4: Very High",
    },
    {
        code: "+240",
        countryCode: "GQ",
        name: "Equatorial Guinea",
        level: "Level 4: Very High",
    },
    {
        code: "+291",
        countryCode: "ER",
        name: "Eritrea",
        level: "Level 4: Very High",
    },
    {
        code: "+372",
        countryCode: "EE",
        name: "Estonia",
        level: "Level 4: Very High",
    },
    {
        code: "+268",
        countryCode: "SZ",
        name: "Swaziland",
        level: "Level 4: Very High",
    },
    {
        code: "+251",
        countryCode: "ET",
        name: "Ethiopia",
        level: "Level 4: Very High",
    },
    { level: "Level 1: Low", name: "Falkland Islands", code: "+500" },
    {
        code: "+298",
        countryCode: "FO",
        name: "Faroe Islands",
        level: "Level 2: Moderate",
    },
    { code: "+679", countryCode: "FJ", name: "Fiji", level: "Level 2: Moder" },
    {
        code: "+358",
        countryCode: "FI",
        name: "Finland",
        level: "Level 4: Very High",
    },
    {
        code: "+33",
        countryCode: "FR",
        name: "France",
        level: "Level 4: Very High",
    },
    {
        code: "+594",
        countryCode: "GF",
        name: "French Guiana",
        level: "Level 4: Very High",
    },
    {
        code: "+689",
        countryCode: "PF",
        name: "French Polynesia",
        level: "Level 4: Very High",
    },
    {
        code: "+241",
        countryCode: "GA",
        name: "Gabon",
        level: "Level 4: Very High",
    },
    {
        code: "+220",
        countryCode: "GM",
        name: "Gambia",
        level: "Level 4: Very High",
    },
    {
        code: "+995",
        countryCode: "GE",
        name: "Georgia",
        level: "Level 4: Very High",
    },
    {
        code: "+49",
        countryCode: "DE",
        name: "Germany",
        level: "Level 4: Very High",
    },
    {
        code: "+233",
        countryCode: "GH",
        name: "Ghana",
        level: "Level 4: Very High",
    },
    {
        code: "+350",
        countryCode: "GI",
        name: "Gibraltar",
        level: "Level 4: Very High",
    },
    {
        code: "+30",
        countryCode: "GR",
        name: "Greece",
        level: "Level 4: Very High",
    },
    { code: "+299", countryCode: "GL", name: "Greenland", level: "Level 1: Low" },
    { code: "+1473", countryCode: "GD", name: "Grenada", level: "Level 1: Low" },
    {
        code: "+590",
        countryCode: "GP",
        name: "Guadeloupe",
        level: "Level 4: Very High",
    },
    {
        code: "+1671",
        countryCode: "GU",
        name: "Guam (U.S.)",
        level: "Level 4: Very High",
    },
    {
        code: "+502",
        countryCode: "GT",
        name: "Guatemala",
        level: "Level 4: Very High",
    },
    {
        code: "+44",
        countryCode: "GG",
        name: "Guernsey",
        level: "Level 2: Moderate",
    },
    {
        code: "+224",
        countryCode: "GN",
        name: "Guinea",
        level: "Level 4: Very High",
    },
    {
        code: "+245",
        countryCode: "GW",
        name: "Guinea-Bissau",
        level: "Level 4: Very High",
    },
    {
        code: "+592",
        countryCode: "GY",
        name: "Guyana",
        level: "Level 4: Very High",
    },
    {
        code: "+509",
        countryCode: "HT",
        name: "Haiti",
        level: "Level 4: Very High",
    },
    {
        code: "+504",
        countryCode: "HN",
        name: "Honduras",
        level: "Level 4: Very High",
    },
    {
        code: "+852",
        countryCode: "HK",
        name: "Hong Kong, China",
        level: "Level 1: Low",
    },
    {
        code: "+36",
        countryCode: "HU",
        name: "Hungary",
        level: "Level 4: Very High",
    },
    {
        code: "+354",
        countryCode: "IS",
        name: "Iceland",
        level: "Level 4: Very High",
    },
    {
        code: "+91",
        countryCode: "IN",
        name: "India",
        level: "Level 4: Very High",
    },
    {
        code: "+62",
        countryCode: "ID",
        name: "Indonesia",
        level: "Level 4: Very High",
    },
    {
        code: "+98",
        countryCode: "IR",
        name: "Iran, Islamic Republic of Persian Gulf",
        level: "Level 4: Very High",
    },
    {
        code: "+964",
        countryCode: "IQ",
        name: "Iraq",
        level: "Level 4: Very High",
    },
    {
        code: "+353",
        countryCode: "IE",
        name: "Ireland",
        level: "Level 4: Very High",
    },
    {
        code: "+44",
        countryCode: "IM",
        name: "Isle of Man",
        level: "Level 1: Low",
    },
    {
        code: "+39",
        countryCode: "IT",
        name: "Italy",
        level: "Level 4: Very High",
    },
    {
        code: "+225",
        countryCode: "CI",
        name: "Cote d'Ivoire",
        level: "Level 1: Low",
    },
    {
        code: "+1876",
        countryCode: "JM",
        name: "Jamaica",
        level: "Level 4: Very High",
    },
    {
        code: "+81",
        countryCode: "JP",
        name: "Japan",
        level: "Level 4: Very High",
    },
    {
        code: "+44",
        countryCode: "JE",
        name: "Jersey",
        level: "Level 4: Very High",
    },
    {
        code: "+962",
        countryCode: "JO",
        name: "Jordan",
        level: "Level 4: Very High",
    },
    {
        code: "+7",
        countryCode: "KZ",
        name: "Kazakhstan",
        level: "Level 4: Very High",
    },
    {
        code: "+254",
        countryCode: "KE",
        name: "Kenya",
        level: "Level 4: Very High",
    },
    { code: "+686", countryCode: "KI", name: "Kiribati", level: "Level 1: Low" },
    {
        code: "+383",
        countryCode: "XK",
        name: "Kosovo",
        level: "Level 4: Very High",
    },
    {
        code: "+965",
        countryCode: "KW",
        name: "Kuwait",
        level: "Level 4: Very High",
    },
    {
        code: "+996",
        countryCode: "KG",
        name: "Kyrgyzstan",
        level: "Level 4: Very High",
    },
    { code: "+856", countryCode: "LA", name: "Laos", level: "Level 1: Low" },
    {
        code: "+371",
        countryCode: "LV",
        name: "Latvia",
        level: "Level 4: Very High",
    },
    {
        code: "+961",
        countryCode: "LB",
        name: "Lebanon",
        level: "Level 4: Very High",
    },
    {
        code: "+266",
        countryCode: "LS",
        name: "Lesotho",
        level: "Level 4: Very High",
    },
    {
        code: "+231",
        countryCode: "LR",
        name: "Liberia",
        level: "Level 4: Very High",
    },
    {
        code: "+218",
        countryCode: "LY",
        name: "Libyan Arab Jamahiriya",
        level: "Level 4: Very High",
    },
    {
        code: "+423",
        countryCode: "LI",
        name: "Liechtenstein",
        level: "Level 4: Very High",
    },
    {
        code: "+370",
        countryCode: "LT",
        name: "Lithuania",
        level: "Level 4: Very High",
    },
    {
        code: "+352",
        countryCode: "LU",
        name: "Luxembourg",
        level: "Level 4: Very High",
    },
    {
        code: "+261",
        countryCode: "MG",
        name: "Madagascar",
        level: "Level 4: Very High",
    },
    {
        code: "+265",
        countryCode: "MW",
        name: "Malawi",
        level: "Level 4: Very High",
    },
    {
        code: "+60",
        countryCode: "MY",
        name: "Malaysia",
        level: "Level 4: Very High",
    },
    {
        code: "+960",
        countryCode: "MV",
        name: "Maldives",
        level: "Level 4: Very High",
    },
    {
        code: "+223",
        countryCode: "ML",
        name: "Mali",
        level: "Level 4: Very High",
    },
    {
        code: "+356",
        countryCode: "MT",
        name: "Malta",
        level: "Level 4: Very High",
    },
    {
        code: "+692",
        countryCode: "MH",
        name: "Marshall Islands",
        level: "Level 1: Low",
    },
    {
        code: "+596",
        countryCode: "MQ",
        name: "Martinique",
        level: "Level 4: Very High",
    },
    {
        code: "+222",
        countryCode: "MR",
        name: "Mauritania",
        level: "Level 4: Very High",
    },
    {
        code: "+230",
        countryCode: "MU",
        name: "Mauritius",
        level: "Level 2: Moderate",
    },
    {
        code: "+262",
        countryCode: "YT",
        name: "Mayotte",
        level: "Level 4: Very High",
    },
    {
        code: "+52",
        countryCode: "MX",
        name: "Mexico",
        level: "Level 4: Very High",
    },
    {
        code: "+691",
        countryCode: "FM",
        name: "Micronesia, Federated States of",
        level: "Level 1: Low",
    },
    {
        code: "+373",
        countryCode: "MD",
        name: "Moldova",
        level: "Level 4: Very High",
    },
    {
        code: "+377",
        countryCode: "MC",
        name: "Monaco",
        level: "Level 4: Very High",
    },
    { code: "+976", countryCode: "MN", name: "Mongolia", level: "Level 1: Low" },
    {
        code: "+382",
        countryCode: "ME",
        name: "Montenegro",
        level: "Level 4: Very High",
    },
    {
        code: "+1664",
        countryCode: "MS",
        name: "Montserrat",
        level: "Level 1: Low",
    },
    {
        code: "+853",
        countryCode: "MC",
        name: "Macao, China",
        level: "Level 1: Low",
    },
    {
        code: "+212",
        countryCode: "MA",
        name: "Morocco",
        level: "Level 4: Very High",
    },
    {
        code: "+258",
        countryCode: "MZ",
        name: "Mozambique",
        level: "Level 4: Very High",
    },
    {
        code: "+264",
        countryCode: "NA",
        name: "Namibia",
        level: "Level 4: Very High",
    },
    { code: "+674", countryCode: "NR", name: "Nauru", level: "Level 1: Low" },
    {
        code: "+977",
        countryCode: "NP",
        name: "Nepal",
        level: "Level 4: Very High",
    },
    {
        code: "+31",
        countryCode: "NL",
        name: "Netherlands",
        level: "Level 4: Very High",
    },
    {
        code: "+687",
        countryCode: "NC",
        name: "New Caledonia",
        level: "Level 1: Low",
    },
    {
        code: "+64",
        countryCode: "NZ",
        name: "New Zealand",
        level: "Level 1: Low",
    },
    {
        code: "+505",
        countryCode: "NI",
        name: "Nicaragua",
        level: "Level 4: Very High",
    },
    {
        code: "+227",
        countryCode: "NE",
        name: "Niger",
        level: "Level 4: Very High",
    },
    {
        code: "+234",
        countryCode: "NG",
        name: "Nigeria",
        level: "Level 4: Very High",
    },
    { code: "+683", countryCode: "NU", name: "Niue", level: "Level 1: Low" },
    {
        code: "+972",
        countryCode: "IS",
        name: "Israel",
        level: "Level 4: Very High",
    },
    {
        code: "+672",
        countryCode: "NF",
        name: "Norfolk Island",
        level: "Level 0: Unknow",
    },
    {
        code: "+850",
        countryCode: "KP",
        name: "Korea, Democratic People's Republic of Korea",
        level: "Level 4: Very High",
    },
    { level: "Level 4: Very High", name: "Macedonia", code: "+389" },
    {
        code: "+1670",
        countryCode: "MP",
        name: "Northern Mariana Islands",
        level: "Level 1: Low",
    },
    {
        code: "+47",
        countryCode: "NO",
        name: "Norway",
        level: "Level 4: Very High",
    },
    {
        code: "+968",
        countryCode: "OM",
        name: "Oman",
        level: "Level 4: Very High",
    },
    {
        code: "+92",
        countryCode: "PK",
        name: "Pakistan",
        level: "Level 4: Very High",
    },
    { code: "+680", countryCode: "PW", name: "Palau", level: "Level 1: Low" },
    { code: "+970", countryCode: "PS", name: "Palestine", level: "Level 1: Low" },
    {
        code: "+507",
        countryCode: "PA",
        name: "Panama",
        level: "Level 4: Very High",
    },
    {
        code: "+675",
        countryCode: "PG",
        name: "Papua New Guinea",
        level: "Level 1: Low",
    },
    {
        code: "+595",
        countryCode: "PY",
        name: "Paraguay",
        level: "Level 4: Very High",
    },
    { code: "+51", countryCode: "PE", name: "Peru", level: "Level 4: Very High" },
    {
        code: "+63",
        countryCode: "PH",
        name: "Philippines",
        level: "Level 4: Very High",
    },
    {
        code: "+64",
        countryCode: "PN",
        name: "Pitcairn Islands (U.K.)",
        level: "Level 4: Very High",
    },
    {
        code: "+48",
        countryCode: "PL",
        name: "Poland",
        level: "Level 4: Very High",
    },
    {
        code: "+351",
        countryCode: "PT",
        name: "Portugal",
        level: "Level 4: Very High",
    },
    {
        code: "+1939",
        countryCode: "PR",
        name: "Puerto Rico",
        level: "Level 4: Very High",
    },
    {
        code: "+974",
        countryCode: "QA",
        name: "Qatar",
        level: "Level 4: Very High",
    },
    {
        code: "+40",
        countryCode: "RO",
        name: "Romania",
        level: "Level 4: Very High",
    },
    {
        code: "+7",
        countryCode: "RU",
        name: "Russia",
        level: "Level 4: Very High",
    },
    { code: "+250", countryCode: "RW", name: "Rwanda", level: "Level 1: Low" },
    { level: "Level 4: Very High", name: "Réunion", code: "+262" },
    { level: "Level 1: Low", name: "Saba", code: "+599" },
    {
        code: "+590",
        countryCode: "BL",
        name: "Saint Barthelemy",
        level: "Level 2: Moderate",
    },
    {
        code: "+290",
        countryCode: "SH",
        name: "Saint Helena",
        level: "Level 1: Low",
    },
    {
        code: "+1869",
        countryCode: "KN",
        name: "Saint Kitts and Nevis",
        level: "Level 1: Low",
    },
    {
        code: "+1758",
        countryCode: "LC",
        name: "Saint Lucia",
        level: "Level 3: High",
    },
    {
        code: "+590",
        countryCode: "MF",
        name: "Saint Martin",
        level: "Level 4: Very High",
    },
    {
        code: "+508",
        countryCode: "PM",
        name: "Saint Pierre and Miquelon",
        level: "Level 1: Low",
    },
    {
        code: "+1784",
        countryCode: "VC",
        name: "Saint Vincent and the Grenadines",
        level: "Level 1: Low",
    },
    { code: "+685", countryCode: "WS", name: "Samoa", level: "Level 1: Low" },
    {
        code: "+378",
        countryCode: "SM",
        name: "San Marino",
        level: "Level 4: Very High",
    },
    {
        code: "+966",
        countryCode: "SA",
        name: "Saudi Arabia",
        level: "Level 4: Very High",
    },
    {
        code: "+221",
        countryCode: "SN",
        name: "Senegal",
        level: "Level 4: Very High",
    },
    {
        code: "+381",
        countryCode: "RS",
        name: "Serbia",
        level: "Level 4: Very High",
    },
    {
        code: "+248",
        countryCode: "SC",
        name: "Seychelles",
        level: "Level 2: Moderate",
    },
    {
        code: "+232",
        countryCode: "SL",
        name: "Sierra Leone",
        level: "Level 1: Low",
    },
    { code: "+65", countryCode: "SG", name: "Singapore", level: "Level 1: Low" },
    { level: "Level 1: Low", name: "Sint Eustatius", code: "+599" },
    { level: "Level 4: Very High", name: "Sint Maarten", code: "+599" },
    {
        code: "+421",
        countryCode: "SK",
        name: "Slovakia",
        level: "Level 4: Very High",
    },
    {
        code: "+386",
        countryCode: "SI",
        name: "Slovenia",
        level: "Level 4: Very High",
    },
    {
        code: "+677",
        countryCode: "SB",
        name: "Solomon Islands",
        level: "Level 4: Very High",
    },
    {
        code: "+252",
        countryCode: "SO",
        name: "Somalia",
        level: "Level 4: Very High",
    },
    {
        code: "+27",
        countryCode: "ZA",
        name: "South Africa",
        level: "Level 4: Very High",
    },
    {
        code: "+500",
        countryCode: "GS",
        name: "South Georgia and the South Sandwich Islands",
        level: "Level 0: Unknow",
    },
    {
        code: "+673",
        countryCode: "BD",
        name: "Brunei Darussalam",
        level: "Level 2: Moderate",
    },
    {
        code: "+82",
        countryCode: "KR",
        name: "Korea, Republic of South Korea",
        level: "Level 2: Moderate",
    },
    {
        code: "+211",
        countryCode: "SS",
        name: "South Sudan",
        level: "Level 4: Very High",
    },
    {
        code: "+34",
        countryCode: "ES",
        name: "Spain",
        level: "Level 4: Very High",
    },
    {
        code: "+94",
        countryCode: "LK",
        name: "Sri Lanka",
        level: "Level 4: Very High",
    },
    {
        code: "+249",
        countryCode: "SD",
        name: "Sudan",
        level: "Level 4: Very High",
    },
    {
        code: "+597",
        countryCode: "SR",
        name: "Suriname",
        level: "Level 4: Very High",
    },
    {
        code: "+46",
        countryCode: "SE",
        name: "Sweden",
        level: "Level 4: Very High",
    },
    {
        code: "+41",
        countryCode: "CH",
        name: "Switzerland",
        level: "Level 4: Very High",
    },
    {
        code: "+963",
        countryCode: "SY",
        name: "Syrian Arab Republic",
        level: "Level 4: Very High",
    },
    { level: "Level 4: Very High", name: "Sao Tome and Principe", code: "+239" },
    {
        code: "+886",
        countryCode: "TW",
        name: "Taiwan, China",
        level: "Level 1: Low",
    },
    {
        code: "+992",
        countryCode: "TJ",
        name: "Tajikistan",
        level: "Level 4: Very High",
    },
    {
        code: "+255",
        countryCode: "TZ",
        name: "Tanzania, United Republic of Tanzania",
        level: "Level 4: Very High",
    },
    { code: "+66", countryCode: "TH", name: "Thailand", level: "Level 1: Low" },
    {
        code: "+670",
        countryCode: "TL",
        name: "Timor-Leste",
        level: "Level 1: Low",
    },
    {
        code: "+228",
        countryCode: "TG",
        name: "Togo",
        level: "Level 4: Very High",
    },
    { code: "+690", countryCode: "TK", name: "Tokelau", level: "Level 1: Low" },
    { code: "+676", countryCode: "TO", name: "Tonga", level: "Level 1: Low" },
    {
        code: "+1868",
        countryCode: "TT",
        name: "Trinidad and Tobago",
        level: "Level 4: Very High",
    },
    {
        code: "+216",
        countryCode: "TN",
        name: "Tunisia",
        level: "Level 4: Very High",
    },
    {
        code: "+90",
        countryCode: "TR",
        name: "Turkey",
        level: "Level 4: Very High",
    },
    {
        code: "+993",
        countryCode: "TM",
        name: "Turkmenistan",
        level: "Level 4: Very High",
    },
    {
        code: "+1649",
        countryCode: "TC",
        name: "Turks and Caicos Islands",
        level: "Level 4: Very High",
    },
    { code: "+688", countryCode: "TV", name: "Tuvalu", level: "Level 1: Low" },
    {
        code: "+256",
        countryCode: "UG",
        name: "Uganda",
        level: "Level 4: Very High",
    },
    {
        code: "+380",
        countryCode: "UA",
        name: "Ukraine",
        level: "Level 4: Very High",
    },
    {
        code: "+971",
        countryCode: "AE",
        name: "United Arab Emirates",
        level: "Level 4: Very High",
    },
    {
        code: "+1",
        countryCode: "US",
        name: "United States",
        level: "Level 4: Very High",
    },
    {
        code: "+44",
        countryCode: "GB",
        name: "United Kingdom",
        level: "Level 4: Very High",
    },
    {
        code: "+598",
        countryCode: "UY",
        name: "Uruguay",
        level: "Level 2: Moderate",
    },
    {
        code: "+358",
        countryCode: "AI",
        name: "Åland Islands",
        level: "Level 2: Moderate",
    },
    {
        code: "+998",
        countryCode: "UZ",
        name: "Uzbekistan",
        level: "Level 4: Very High",
    },
    { code: "+678", countryCode: "VU", name: "Vanuatu", level: "Level 1: Low" },
    {
        code: "+58",
        countryCode: "VE",
        name: "Venezuela, Bolivarian Republic of Venezuela",
        level: "Level 4: Very High",
    },
    { code: "+84", countryCode: "VN", name: "Vietnam", level: "Level 1: Low" },
    {
        code: "+1340",
        countryCode: "VI",
        name: "Virgin Islands, U.S.",
        level: "Level 4: Very High",
    },
    { level: "Level 0: Unknow", name: "Western Sahara", code: "+212" },
    {
        code: "+967",
        countryCode: "YE",
        name: "Yemen",
        level: "Level 4: Very High",
    },
    {
        code: "+260",
        countryCode: "ZM",
        name: "Zambia",
        level: "Level 4: Very High",
    },
    {
        code: "+263",
        countryCode: "ZW",
        name: "Zimbabwe",
        level: "Level 4: Very High",
    },
];